### ISSUE TITLE
Foal model grazing

### ISSUE THREAD

**Issue by sekelsta** [Fuzss/simplifiedhorses#1]
When the foals graze, their heads detach.

**Comment by sekelsta** [comment]
(Meant to add, this is on 1.15)
Edit: See pull request

**Comment by Fuzss** [comment]
Thanks, focus of the mod has now changed to only include hud improvements when riding, so the old horse model has been removed. If you're still interested in the old horse model, I can recommend this mod instead: [Realistic Horse Genetics](https://www.curseforge.com/minecraft/mc-mods/realistic-horse-genetics) (it has many more features, but the old horse model is one of them)
