### ISSUE TITLE
Horse model broken

### ISSUE THREAD

**Issue by Sablehaven** [Fuzss/simplifiedhorses#4]
![2020-08-08_16 47 46](https://user-images.githubusercontent.com/69405908/89721819-f2336e00-d996-11ea-8560-0f0b0e0bbf77.png)

This error happens with both naturally generated and spawned horses, I have no other mods installed and am using 1.15.2 Forge 31.2.0.

I have tried multiple worlds and restarting minecraft.

**Comment by Fuzss** [comment]
The order of your resource packs is wrong. The mod resources pack needs to be above the vanilla one. Right now the new horse texture is used on the old model which doesn't quite add up as you can see.
