### ISSUE TITLE
1.15 Horses don't have ears

### ISSUE THREAD

**Issue by Meltrind** [Fuzss/simplifiedhorses#5]
Title says it all..

**Comment by Fuzss** [comment]
Thanks, focus of the mod has now changed to only include hud improvements when riding, so the old horse model has been removed. If you're still interested in the old horse model, I can recommend this mod instead: [Realistic Horse Genetics](https://www.curseforge.com/minecraft/mc-mods/realistic-horse-genetics) (it has many more features, but the old horse model is one of them)
